### PR TITLE
Set /Users/Jordy to $HOME

### PR DESCRIPTION
**Pull request by WarpWing**
So I was looking at the latest commit for the Dotfiles. Under this: 
https://github.com/atidyshirt/MacOS-Dotfiles/commit/90ef36351750cc001b3f428e7699592ede924d6a 

You had it set as 
export PATH="/Users/jordy/bin:$PATH"

instead of:

export PATH="$HOME/bin:$PATH"

xd

PS: I just find it funny that this was a push by you to streamline user experience yet it was /Users/Jordy signifying that you would only use (unless you made a mistake and don't worry, we all do :) )

### CODE REVIEW

**Comment by atidyshirt** [comment]
Haha, I think it's time I go through all the paths and make sure they are general :), just a mistake.

**Comment by WarpWing** [comment]
I can always do that for you. (I got time to kill dw xd) Also are you going to merge or ?

**Comment by atidyshirt** [comment]
Will do, at work atm, when I get home I will merge.

**Comment by WarpWing** [comment]
Have fun at work xd

**Comment by WarpWing** [comment]
Btw, if you have time. Check out this
https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification
It's how I got dat Verified next to every commit.

**Review by atidyshirt — APPROVED** [review]

**Review by atidyshirt — APPROVED** [review]

**Comment by WarpWing** [comment]
For the record, I'm pretty sure this is all the $HOME conflicts :D

**Comment by atidyshirt** [comment]
There are many more path errors in the .zshrc, .bashrc and other files around the place, I will fix this and make a commit.

**Pull request closed without merging**
