### PR TITLE
Simplifying install script - intergrating Curl

### PR DESCRIPTION
**Pull request by WarpWing**
This is just a yabairc config example (its mine) but I think it might be benefical for people to at least have a example of a yabairc cfg file :)

tldr: Added yabairc (you should probably remove my config and replace it ur own. You know, because it's your own dotfiles

### CODE REVIEW

**Comment by WarpWing** [comment]
I just updated the script. It turns out we can have it all in one script! We just don't need sudo WITH the bashscript. See changes for reasoning.

I also made this one simple command for calling the install script 
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/WarpWing/MacOS-Dotfiles/master/install.sh)"

Check out the code and comment on this pull req if you have any questions :)

PS: This is all beta. I recommend you test this command
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/WarpWing/MacOS-Dotfiles/master/install.sh)"

As this is reversed engineered from how the homebrew install was able to install with one simple command. It works for me on my scripts but so far, it's pretty stable on my end :)
PPS: I got a lot of time to kill today :)

**Comment by atidyshirt** [comment]
The yabairc is in the dotfiles, just in the .config/yabai/.yabairc

**Comment by WarpWing** [comment]
I just realized that this script may not work because it lacks a chmod permission
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/WarpWing/MacOS-Dotfiles/master/install.sh)"
BUT it SHOULD ask for password mid execution so I mean, still works

**Comment by atidyshirt** [comment]
Ill update the name to point to master branch, and will merge shortly 👍

**Comment by WarpWing** [comment]
Thank you Jordan! Also please check out my fix to your fork of simple-bar when you have the chance

https://github.com/atidyshirt/simple-bar/pull/1

**Pull request merged**
