### PR TITLE
Quick Thing

### PR DESCRIPTION
**Pull request by WarpWing**
Screen Shot 2020-07-12 at 11 45 35 AM
Could you just merge the changes I have now? If it isn't too much trouble, github is giving me problems with attempting to pull req from your repo to my fork of it. It's a merge error

### CODE REVIEW

**Review by atidyshirt — APPROVED** [review]

**Comment by WarpWing** [comment]
This is weird, why doesn't it merge on approval? Does have to be done manually?

**Comment by atidyshirt** [comment]
> This is weird, why doesn't it merge on approval? Does have to be done manually?

I'm not sure, I think its because in the main branch, these changes had already been made, as I went through all the files manually, but on your remote branch they had not been made, I think you might need to merge atidyshirt/MacOS-Dotfiles ~> WarpWing/MacOS-Dotfiles, and this should resolve the conflict (not sure though).

**Comment by WarpWing** [comment]
Hmmm, well I might need to delete my current fork as it's a bit glitchy for me 
Also, I recommend you look at this since I noticed on your PFP that you are a Comp Sci Student 
https://education.github.com/pack 
Trust me, free stuff is cool stuff

**Comment by atidyshirt** [comment]
> Hmmm, well I might need to delete my current fork as it's a bit glitchy for me
> Also, I recommend you look at this since I noticed on your PFP that you are a Comp Sci Student
> https://education.github.com/pack
> Trust me, free stuff is cool stuff

Thanks man :)

**Comment by WarpWing** [comment]
> > Hmmm, well I might need to delete my current fork as it's a bit glitchy for me
> > Also, I recommend you look at this since I noticed on your PFP that you are a Comp Sci Student
> > https://education.github.com/pack
> > Trust me, free stuff is cool stuff
> 
> Thanks man :)

From a student to a student :), trust me you get a free domain, you get gitkraken pro and a bunch of other cool stuff. I got  free github pro from it

**Pull request closed without merging**
